### ISSUE TITLE
[Bug]: nestjs/graphql 9 breaks the interceptro

### ISSUE THREAD

**Issue by roderik** [jmcdo29/ogma#626]
## Current behavior

```
[2021-08-26T14:03:10.537Z] [ERROR] [eris] [development] [40475]  [ExceptionsHandler] TypeError: Cannot set property 'requestId' of undefined
    at GraphQLParser.setRequestId (/Users/roderik/Development/bpaas/node_modules/@ogma/platform-express/lib/express-interceptor.service.js:32:23)
    at DelegatorService.setRequestId (/Users/roderik/Development/bpaas/node_modules/@ogma/nestjs-module/lib/interceptor/providers/delegator.service.js:27:22)
    at OgmaInterceptor.intercept (/Users/roderik/Development/bpaas/node_modules/@ogma/nestjs-module/lib/interceptor/ogma.interceptor.js:40:23)
    at /Users/roderik/Development/bpaas/node_modules/@nestjs/core/interceptors/interceptors-consumer.js:23:36
    at InterceptorsConsumer.intercept (/Users/roderik/Development/bpaas/node_modules/@nestjs/core/interceptors/interceptors-consumer.js:25:24)
    at target (/Users/roderik/Development/bpaas/node_modules/@nestjs/core/helpers/external-context-creator.js:77:60)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at /Users/roderik/Development/bpaas/node_modules/@nestjs/core/helpers/external-proxy.js:9:24
    at Object.createAsyncIterator (/Users/roderik/Development/bpaas/node_modules/@nestjs/graphql/dist/utils/async-iterator.util.js:6:27)
```

**Comment by jmcdo29** [comment]
I have a feeling this is related to the fact that my packages are still only _technically_ for Nest v7. I need to upgrade them, but will probably need to re-write some code to make it doable, due to using an underlying package that still isn't updated. I'll try to work on that soon

**Comment by jmcdo29** [comment]
I have some code up that's ready for the Nest v8 upgrade and passes integration tests. I'm going to be publishing it later this week, hopefully after I get a new docs site up as well, just as an overall change that works really well together.

**Comment by jmcdo29** [comment]
@roderik Okay, can you give `@ogma/nestjs-module@3` a shot, and if it's still having an issue provide a minimum reproduction?

**Comment by roderik** [comment]
Yeah sorry, we are in the last 10% stretch of release (90% of the work still to do) so I quickly ripped out ogma and went back to the included logger until we get our heads above water.

**Comment by jmcdo29** [comment]
I have `@nestjs/grpahql@9.1.1` being used in the integration tests and have no issue with it. `@nestjs/graphql@10` might be a different story with the built in apollo and mercurius support, but that should be a different issue. I'm going to close this as it looks resolved to me, if not and you can provide a minimum reproduction, please do so
